// GROUP ACTIONS
export const ADD_GROUP = "ADD_GROUP";
export const UPDATE_GROUP = "UPDATE_GROUP";
export const DELETE_GROUP = "DELETE_GROUP";

// FIELD ACTIONS
export const ADD_FIELD = "ADD_FIELD";
export const UPDATE_FIELD = "UPDATE_FIELD";
export const DELETE_FIELD = "DELETE_FIELD";

// CONSTRAINT ACTIONS
export const ADD_CONSTRAINT = "ADD_CONSTRAINT";
export const UPDATE_CONSTRAINT = "UPDATE_CONSTRAINT";
export const DELETE_CONSTRAINT = "DELETE_CONSTRAINT";

// VALUE ACTIONS
export const ADD_VALUE = "ADD_VALUE";
export const DELETE_VALUE = "DELETE_VALUE";
